// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParkingSystem.DBContext;

#nullable disable

namespace SmartParkingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519125328_AddEasyPaisaPhoneToCarParking")]
    partial class AddEasyPaisaPhoneToCarParking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarParking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("EasyPaisaPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("carNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("parkingEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("parkingID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("parkingStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("totalAmount")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("parkingID");

                    b.ToTable("CarParkings");
                });

            modelBuilder.Entity("SmartParkingSystem.Models.Parking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Parkingtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("priceperhour")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("CarParking", b =>
                {
                    b.HasOne("SmartParkingSystem.Models.Parking", "Parking")
                        .WithMany("CarParkings")
                        .HasForeignKey("parkingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("SmartParkingSystem.Models.Parking", b =>
                {
                    b.Navigation("CarParkings");
                });
#pragma warning restore 612, 618
        }
    }
}
